### ISSUE TITLE
shape '[512, 256, 3, 3]' is invalid for input of size 357392

### ISSUE THREAD

**Issue by noobliang** [tanluren/yolov3-channel-and-layer-pruning#11]
你好,  我训练自己的数据,经过基础训练,稀疏训练, 和shortcut_prune剪枝, tensorboard 和 剪枝结果都是正常的, 但是最后我用剪枝后的权重跑detect.py 时候报错了,shape '[512, 256, 3, 3]' is invalid for input of size 357392..  请问经过shortcut_prune剪枝之后得到的权重是否还要处理?...

**Comment by noobliang** [comment]
> 你好, 我训练自己的数据,经过基础训练,稀疏训练, 和shortcut_prune剪枝, tensorboard 和 剪枝结果都是正常的, 但是最后我用剪枝后的权重跑detect.py 时候报错了,shape '[512, 256, 3, 3]' is invalid for input of size 357392.. 请问经过shortcut_prune剪枝之后得到的权重是否还要处理?...

蠢了,,, 刚刚发现还生成了配置文件,没用上=_=

**Comment by tanluren** [comment]
嗯嗯剪枝后模型结构发生了改变，所以会生成新的cfg，加上权重你还可以移植到其他框架。剪通道的话试试slim prune效果可能更好哦

**Comment by noobliang** [comment]
> 嗯嗯剪枝后模型结构发生了改变，所以会生成新的cfg，加上权重你还可以移植到其他框架。剪通道的话试试slim prune效果可能更好哦

恩恩， 感谢你的回复，  我想问下，你有没有尝试过 将导出的onnx 转换成tensorrt, 这一步我遇到了困难，一直转不成功。

**Comment by Gaondong** [comment]
@noobliang 感谢推荐 哈哈 从别的项目过来的，看了一遍issues又看到了你的评论，可否留个联系方式，我后面也要做onnx tensorrt，可以一起讨论

**Comment by noobliang** [comment]
微信，xlm99249359
发自我的iPhone

------------------ Original ------------------

**Comment by Gaondong** [comment]
@noobliang 我的微信gjdfighting，你的账号搜索不到
