### ISSUE TITLE
两类目标检测，精度为0

### ISSUE THREAD

**Issue by noobliang** [tanluren/yolov3-channel-and-layer-pruning#12]
单类目标检测没问题，效果很好，但是同一个数据集，我检测两个类之后，刚开始训练精度非常低，0.008，经过几个epoch就降到0了， 尝试过调小学习率，增大batch，还是这样。请问有大佬碰到过吗。
![Screenshot from 2019-12-05 14-14-27](https://user-images.githubusercontent.com/41882150/70208860-9b232c80-1769-11ea-9016-d0dd1b32b071.png)

**Comment by tanluren** [comment]
你好，可以看看你训练的命令吗？有没有使用预训练权重？数据处理有没有问题，如cfg的设置和label，names等是否对应

**Comment by noobliang** [comment]
> 你好，可以看看你训练的命令吗？有没有使用预训练权重？数据处理有没有问题，如cfg的设置和label，names等是否对应

你好， 数据集我是之前跑过yolov3-tiny的，我也查看了，没什么问题， 参数配置我也分别检查过了。不知道为什么会这样，很奇怪。
Namespace(accumulate=2, adam=False, arc='defaultpw', batch_size=16, bucket='', cache_images=False, cfg='cfg/yolov3-spp.cfg', data='data/car_crop.data', device='0', epochs=100, evolve=False, img_size=416, img_weights=False, multi_scale=False, name='', nosave=False, notest=False, prebias=False, prune=1, rect=False, resume=False, s=0.001, sr=False, transfer=False, var=None, weights='weights/yolov3-spp.weights')

**Comment by tanluren** [comment]
分类损失太高，看看label里面的id是不是有问题

**Comment by noobliang** [comment]
> 分类损失太高，看看label里面的id是不是有问题

非常感谢作者大哥回复 ，但是我发现一个奇怪的问题。数据集我没动，关掉数据增强就没问题了，刚刚训练了几个小时，基础训练没问题了。看着损失下降很开心，哈哈。
![Screenshot from 2019-12-06 11-09-57](https://user-images.githubusercontent.com/41882150/70299867-0dab0f80-1831-11ea-8201-52a8309d7be0.png)
我多次测试 ，发现只要开启数据增强，就出问题。
![Screenshot from 2019-12-06 13-53-14](https://user-images.githubusercontent.com/41882150/70299934-36330980-1831-11ea-9e34-6de5e734ba33.png)
我的数据图片尺寸小于416, 一张图就一两个目标，而且两个类别很相似，我不知道这有没有什么影响。

**Comment by tanluren** [comment]
哈哈有意思
