### ISSUE TITLE
基础训练最后一次prec急剧下降

### ISSUE THREAD

**Issue by SangerY** [tanluren/yolov3-channel-and-layer-pruning#122]
![(T435X$EE(3IHXR(`5BPEEK](https://user-images.githubusercontent.com/12136347/96408085-57b49e00-1215-11eb-8af4-3f4f202ee581.png)

基础训练yolov3，最后一次prec急剧下降，是正常的吗？训练代码如下：
python train.py --cfg myData/yolov3.cfg --data myData/electric.data --weights myData/yolov3.weights --epochs 100 --batch-size 8 --multi-scale

**Comment by DerekSunYH** [comment]
请问你的electric.data中train和valid的数据比例是多少？

**Comment by SangerY** [comment]
> 请问你的electric.data中train和valid的数据比例是多少？

一般是8:2，这个问题后来说是因为最后一个epoch时，阈值设置为0.01导致。

**Comment by DerekSunYH** [comment]
好的 。谢谢

**Comment by xunan12138** [comment]
> > 请问你的electric.data中train和valid的数据比例是多少？
> 
> 一般是8:2，这个问题后来说是因为最后一个epoch时，阈值设置为0.01导致。

那请问这种情况需要怎样修改呢？
