### ISSUE TITLE
2080ti上面训练，显存溢出

### ISSUE THREAD

**Issue by deep-practice** [tanluren/yolov3-channel-and-layer-pruning#21]
2080ti上面，网络输入大小416，把batch size设为8都会显存溢出，这是正常的吗。
![image](https://user-images.githubusercontent.com/54052915/70496566-02b2f080-1b4b-11ea-9d8d-a98d325723e4.png)
![image](https://user-images.githubusercontent.com/54052915/70496659-54f41180-1b4b-11ea-9685-861b02130aa9.png)

**Comment by deep-practice** [comment]
Solved

**Comment by liuxundd** [comment]
我也遇到这个问题 ，请问怎么解决的？
