### ISSUE TITLE
通道剪枝错误, get_mask2 未找到..

### ISSUE THREAD

**Issue by Byronnar** [tanluren/yolov3-channel-and-layer-pruning#24]
Epoch   gpu_mem      GIoU       obj       cls     total      soft   targets  img_size
  0%|                                                                                                                                                                                                 | 0/309 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 534, in <module>
    train()  # train normally
  File "train.py", line 313, in train
    idx2mask = get_mask2(model, prune_idx, 0.95)
NameError: name 'get_mask2' is not defined
  0%|                                                                                                                                                                                                 | 0/309 [00:00<?, ?it/s]
请问是不是 命名有问题? 
我改成 get_mask之后也报错

**Comment by tanluren** [comment]
嗯。。。实验代码，已删掉，使用新版本
