### ISSUE TITLE
源码实现有问题啊？

### ISSUE THREAD

**Issue by Charles-png** [tanluren/yolov3-channel-and-layer-pruning#3]
torch安装需要python64位，但是报错OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
改正32位的python版本，torch又会报错，报错为找不到torch._C

**Comment by tanluren** [comment]
pytorch安装根据官网命令即可，https://pytorch.org/get-started/locally/， 找不到torch._C往往是python版本或者numpy版本不匹配。亲测1.1，1.2都可运行这套代码。
