### ISSUE TITLE
大佬您好，detect.py调用摄像头没有识别结果

### ISSUE THREAD

**Issue by JiangMecca** [tanluren/yolov3-channel-and-layer-pruning#38]
u版的输入如下命令python detect.py --cfg cfg/yolov3.cfg --weights weights/yolov3.weights --source 0 --conf-thres 0.1可以调用摄像头且正常识别。
没看到您有介绍如何test或detect的教程，所以我在这里也这么使用，但是无法识别，如下图，cfg也改成test模式了。请问什么原因。
![image](https://user-images.githubusercontent.com/32949036/71649055-8032e080-2d46-11ea-8d0c-0e3a0f619d8a.png)

**Comment by tanluren** [comment]
这是因为在load_darknet_weights那里改了规则，如果权重名字是yolov3.weights或者yolov3-spp.weights会跳过三个输出卷积，这是为了拿来训练自己数据集时初始化权重，加快收敛。所以你拿yolov3.weights检测物体的话会因为没完整加载权重而无法检测，如果你想用它，就改下名字可以了

**Comment by tanluren** [comment]
这个项目讨论的重点是剪枝，test和detect都是用原版U的，看看原版的介绍或者看代码就清楚了

**Comment by JiangMecca** [comment]
> 这个项目讨论的重点是剪枝，test和detect都是用原版U的，看看原版的介绍或者看代码就清楚了
谢谢大佬
