### ISSUE TITLE
基础训练的时候,prune默认是1吗

### ISSUE THREAD

**Issue by noobliang** [tanluren/yolov3-channel-and-layer-pruning#9]
大神,你好, 想问下,在稀疏训练之前 , 必须要 先经过基础训练是吧?,还有 基础训练的时候prune默认是1,不用改把?

**Comment by tanluren** [comment]
你好，如果数据集比较简单可以直接跑稀疏训练，但一般还是建议先跑个好的baseline。prune默认是1，建议也是用1，是配合-sr开启稀疏训练后用的，没开启-sr的话不会用到prune选项。

**Comment by noobliang** [comment]
> 你好，如果数据集比较简单可以直接跑稀疏训练，但一般还是建议先跑个好的baseline。prune默认是1，建议也是用1，是配合-sr开启稀疏训练后用的，没开启-sr的话不会用到prune选项。

好的,非常感谢!
