### ISSUE TITLE
AB版本训练出来的权重文件，使用第一种方法剪枝后map降低到0.01以下

### ISSUE THREAD

**Issue by zhuhuangru** [tanluren/yolov3-channel-and-layer-pruning#93]
权重文件采用AB版本的darknet训练得到，计算map大概在0.66左右。
使用yolov3可以进行推理，测试，转化为pt模型后也一切正常。

问题在于使用prune.py进行剪枝后，map直接降低到0.01以下，求问，如何解决？

**Comment by zhuhuangru** [comment]
看到很多issue提到pytorch和darknet的权重文件不一样，但是为何推理时候又没有问题呢？？？

**Comment by zhuhuangru** [comment]
自己的问题。没有进行稀疏训练。回头测试完再来回复。谢谢。

**Comment by ForrestHeiYing** [comment]
@zhuhuangru 基于AB版本的darknet 训练的yolov3，可以直接用本工程进行稀疏训练和剪枝吗
效果怎么样呢？
